let Merida = sprites.create(assets.image`Merida`, SpriteKind.Player)
let Warrior = sprites.create(assets.image`warrior`, SpriteKind.Player)
let warrior_2 = sprites.create(assets.image`warrior_2`, SpriteKind.Player)
Merida.say("Hello Brothers")
Warrior.say("hello sister")
warrior_2.say("hello sister")
Merida.setPosition(30, 47)
Warrior.setPosition(142, 53)
warrior_2.setPosition(66, 78)
